name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Test e2e
        run: pnpm test:e2e

      - name: Check dist
        run: ls -la dist || exit 1  # Fail if dist is empty/missing

  # Optional: Docker build check (if you want to test Docker setup)
  docker-build:
    runs-on: ubuntu-latest
    needs: build  # Run after successful build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker-compose build --no-cache
